### ISSUE TITLE
Return Cow<str>

### ISSUE THREAD

**Issue by lexoliu** [bt/rust_urlencoding#10]
https://docs.rs/urlencoding/1.1.1/src/urlencoding/lib.rs.html#9-16

`urlencoding::encode` and `urlencoding::decode` might return to `Cow<str>`.If we parse the ascii string, we don't need to copy it.

**Comment by kornelski** [comment]
This is implemented in 1.3.1

The development happens in another repo: https://github.com/kornelski/rust_urlencoding

**Comment by lexoliu** [comment]
Seem that this repository has been deprecated, it was moved to [https://github.com/kornelski/rust_urlencoding]. So I close the issue.
