### ISSUE TITLE
State of `urlencoding`

### ISSUE THREAD

**Issue by soerenmeier** [bt/rust_urlencoding#11]
I like this crate, it's easy and lightweight, however some issues and feature requests are still unanswered.
As i read in #9 @kornelski offered to help maintain this crate.
Can we expect urlencoding to be maintained and maybe get some new features like #5, #10 or https://github.com/kornelski/rust_urlencoding/pull/1 or should we move to another one?
There seems to be around 70 other crates depending on urlencoding: https://crates.io/crates/urlencoding/reverse_dependencies.
Even if this crate is small it should probably have an active/passiv maintainer.
@kornelski if your still maintaining this crate, maybe you could get access rights to this repository or create a new one, not a fork?
If you @bt and @kornelski don't wan't to maintain this crate anymore, I would volunteer.
As a last resort there's always the possibility to file unmaintained https://github.com/RustSec/advisory-db/issues/173.

@kornelski hope you forgive me for not waiting longer than 20 days for a response in https://github.com/kornelski/rust_urlencoding/pull/1.

**Comment by kornelski** [comment]
It's maintained at https://github.com/kornelski/rust_urlencoding (https://lib.rs/urlencoding)

**Comment by soerenmeier** [comment]
Yes i saw that, the problem is there you can't open issues.

**Comment by soerenmeier** [comment]
Anyway, thanks for resolving this issue so quickly.
