### ISSUE TITLE
Decoding is implemented but unreleased.

### ISSUE THREAD

**Issue by jasonwyatt** [bt/rust_urlencoding#3]
I was hoping to use this crate in a project of mine but I saw that `decode` isn't yet released, even though I see it's implemented in the source here. Is there any ETA on a release with decoding?

**Comment by bt** [comment]
Hey there @jasonwyatt!

I just received the PR to implement decode yesterday and I merged it in. I have to clean up the `README` a bit first to show an example of `decode` and then I'll get it released. Should be out within the next 24-48 hours.

Thanks for reminding me!

**Comment by jasonwyatt** [comment]
Oh nice! I didn't realize that the `decode` code was so new :)

**Comment by bt** [comment]
Just released `1.0.0` with `decode`. Let me know if that solves your issue! 👍

**Comment by jasonwyatt** [comment]
Looks great! Thanks :)
