### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kornelski** [bt/rust_urlencoding#9]
@bt Are you planning to make a release with the recent changes?

If you need help maintaining the crate, I'm happy to help - add me on crates.io

**Comment by bt** [comment]
Hey @kornelski, thanks for reaching out!

To be honest, I've moved on from Rust primarily to Golang now, so I don't really maintain much of the contributions that I had in Rust.

I've gone ahead and added you on crates.io as an owner, let me know if it works :)

**Comment by kornelski** [comment]
Got it. Thank you.
